/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthEnvironmentsIndexRouteImport } from './routes/_auth/environments/index'
import { Route as AuthAppsAppIdRouteImport } from './routes/_auth/apps/$appId'
import { Route as AuthEnvironmentsEnvironmentIdRouteRouteImport } from './routes/_auth/environments/$environmentId/route'
import { Route as AuthEnvironmentsEnvironmentIdIndexRouteImport } from './routes/_auth/environments/$environmentId/index'
import { Route as AuthEnvironmentsEnvironmentIdCertificatesRouteImport } from './routes/_auth/environments/$environmentId/certificates'
import { Route as AuthEnvironmentsEnvironmentIdAppsRouteImport } from './routes/_auth/environments/$environmentId/apps'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEnvironmentsIndexRoute = AuthEnvironmentsIndexRouteImport.update({
  id: '/environments/',
  path: '/environments/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppsAppIdRoute = AuthAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEnvironmentsEnvironmentIdRouteRoute =
  AuthEnvironmentsEnvironmentIdRouteRouteImport.update({
    id: '/environments/$environmentId',
    path: '/environments/$environmentId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthEnvironmentsEnvironmentIdIndexRoute =
  AuthEnvironmentsEnvironmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthEnvironmentsEnvironmentIdRouteRoute,
  } as any)
const AuthEnvironmentsEnvironmentIdCertificatesRoute =
  AuthEnvironmentsEnvironmentIdCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthEnvironmentsEnvironmentIdRouteRoute,
  } as any)
const AuthEnvironmentsEnvironmentIdAppsRoute =
  AuthEnvironmentsEnvironmentIdAppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => AuthEnvironmentsEnvironmentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/setup': typeof SetupRoute
  '/environments/$environmentId': typeof AuthEnvironmentsEnvironmentIdRouteRouteWithChildren
  '/apps/$appId': typeof AuthAppsAppIdRoute
  '/environments/': typeof AuthEnvironmentsIndexRoute
  '/environments/$environmentId/apps': typeof AuthEnvironmentsEnvironmentIdAppsRoute
  '/environments/$environmentId/certificates': typeof AuthEnvironmentsEnvironmentIdCertificatesRoute
  '/environments/$environmentId/': typeof AuthEnvironmentsEnvironmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/': typeof AuthIndexRoute
  '/apps/$appId': typeof AuthAppsAppIdRoute
  '/environments': typeof AuthEnvironmentsIndexRoute
  '/environments/$environmentId/apps': typeof AuthEnvironmentsEnvironmentIdAppsRoute
  '/environments/$environmentId/certificates': typeof AuthEnvironmentsEnvironmentIdCertificatesRoute
  '/environments/$environmentId': typeof AuthEnvironmentsEnvironmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/setup': typeof SetupRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/environments/$environmentId': typeof AuthEnvironmentsEnvironmentIdRouteRouteWithChildren
  '/_auth/apps/$appId': typeof AuthAppsAppIdRoute
  '/_auth/environments/': typeof AuthEnvironmentsIndexRoute
  '/_auth/environments/$environmentId/apps': typeof AuthEnvironmentsEnvironmentIdAppsRoute
  '/_auth/environments/$environmentId/certificates': typeof AuthEnvironmentsEnvironmentIdCertificatesRoute
  '/_auth/environments/$environmentId/': typeof AuthEnvironmentsEnvironmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/environments/$environmentId'
    | '/apps/$appId'
    | '/environments/'
    | '/environments/$environmentId/apps'
    | '/environments/$environmentId/certificates'
    | '/environments/$environmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/'
    | '/apps/$appId'
    | '/environments'
    | '/environments/$environmentId/apps'
    | '/environments/$environmentId/certificates'
    | '/environments/$environmentId'
  id:
    | '__root__'
    | '/_auth'
    | '/setup'
    | '/_auth/'
    | '/_auth/environments/$environmentId'
    | '/_auth/apps/$appId'
    | '/_auth/environments/'
    | '/_auth/environments/$environmentId/apps'
    | '/_auth/environments/$environmentId/certificates'
    | '/_auth/environments/$environmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/environments/': {
      id: '/_auth/environments/'
      path: '/environments'
      fullPath: '/environments/'
      preLoaderRoute: typeof AuthEnvironmentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/apps/$appId': {
      id: '/_auth/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AuthAppsAppIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/environments/$environmentId': {
      id: '/_auth/environments/$environmentId'
      path: '/environments/$environmentId'
      fullPath: '/environments/$environmentId'
      preLoaderRoute: typeof AuthEnvironmentsEnvironmentIdRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/environments/$environmentId/': {
      id: '/_auth/environments/$environmentId/'
      path: '/'
      fullPath: '/environments/$environmentId/'
      preLoaderRoute: typeof AuthEnvironmentsEnvironmentIdIndexRouteImport
      parentRoute: typeof AuthEnvironmentsEnvironmentIdRouteRoute
    }
    '/_auth/environments/$environmentId/certificates': {
      id: '/_auth/environments/$environmentId/certificates'
      path: '/certificates'
      fullPath: '/environments/$environmentId/certificates'
      preLoaderRoute: typeof AuthEnvironmentsEnvironmentIdCertificatesRouteImport
      parentRoute: typeof AuthEnvironmentsEnvironmentIdRouteRoute
    }
    '/_auth/environments/$environmentId/apps': {
      id: '/_auth/environments/$environmentId/apps'
      path: '/apps'
      fullPath: '/environments/$environmentId/apps'
      preLoaderRoute: typeof AuthEnvironmentsEnvironmentIdAppsRouteImport
      parentRoute: typeof AuthEnvironmentsEnvironmentIdRouteRoute
    }
  }
}

interface AuthEnvironmentsEnvironmentIdRouteRouteChildren {
  AuthEnvironmentsEnvironmentIdAppsRoute: typeof AuthEnvironmentsEnvironmentIdAppsRoute
  AuthEnvironmentsEnvironmentIdCertificatesRoute: typeof AuthEnvironmentsEnvironmentIdCertificatesRoute
  AuthEnvironmentsEnvironmentIdIndexRoute: typeof AuthEnvironmentsEnvironmentIdIndexRoute
}

const AuthEnvironmentsEnvironmentIdRouteRouteChildren: AuthEnvironmentsEnvironmentIdRouteRouteChildren =
  {
    AuthEnvironmentsEnvironmentIdAppsRoute:
      AuthEnvironmentsEnvironmentIdAppsRoute,
    AuthEnvironmentsEnvironmentIdCertificatesRoute:
      AuthEnvironmentsEnvironmentIdCertificatesRoute,
    AuthEnvironmentsEnvironmentIdIndexRoute:
      AuthEnvironmentsEnvironmentIdIndexRoute,
  }

const AuthEnvironmentsEnvironmentIdRouteRouteWithChildren =
  AuthEnvironmentsEnvironmentIdRouteRoute._addFileChildren(
    AuthEnvironmentsEnvironmentIdRouteRouteChildren,
  )

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthEnvironmentsEnvironmentIdRouteRoute: typeof AuthEnvironmentsEnvironmentIdRouteRouteWithChildren
  AuthAppsAppIdRoute: typeof AuthAppsAppIdRoute
  AuthEnvironmentsIndexRoute: typeof AuthEnvironmentsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthEnvironmentsEnvironmentIdRouteRoute:
    AuthEnvironmentsEnvironmentIdRouteRouteWithChildren,
  AuthAppsAppIdRoute: AuthAppsAppIdRoute,
  AuthEnvironmentsIndexRoute: AuthEnvironmentsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
